# README gallery generator.
#
#   julia +1.12 --project=CanvasMakie/test reftests/gen_readme_gallery.jl
#
# Renders every core-corpus scene through the WasmMakie STATIC CORE — the
# exact pipeline that ships to wasm (typed Figure/Axis API → RecordingCtx
# command stream → the bundled JS replayer in Chromium) — into
# assets/gallery/<slug>.png, then rewrites the README section between the
# GALLERY markers. What renders here is what works in the browser; the
# corpus is the ratchet (reftests/scores_core_corpus.tsv), so the gallery
# can only grow.
import WasmMakie
using CanvasMakie   # commands_to_png: the Chromium replay harness

include(joinpath(@__DIR__, "core_corpus.jl"))

const W = 400
const H = 300
const GALLERY = normpath(joinpath(@__DIR__, "..", "assets", "gallery"))
const README = normpath(joinpath(@__DIR__, "..", "README.md"))

slugify(name) = replace(replace(name, r"^(core|recipes): " => ""),
                        r"[^a-zA-Z0-9]+" => "-") |> lowercase |> s -> strip(s, '-')

mkpath(GALLERY)
entries = Tuple{String,String}[]   # (display name, slug)
for scene in CoreCorpus.CORPUS
    name = replace(scene.name, r"^(core|recipes): " => "")
    slug = slugify(scene.name)
    wfig = WasmMakie.Figure(size = (W, H))
    scene.build_core(wfig)
    rctx = WasmMakie.RecordingCtx()
    WasmMakie.render!(wfig, rctx)
    png = CanvasMakie.commands_to_png(rctx, W, H)
    write(joinpath(GALLERY, slug * ".png"), png)
    push!(entries, (name, slug))
    println(rpad(name, 32), "→ assets/gallery/", slug, ".png")
end

# README gallery table, 3 per row
cells = ["**$(name)**<br><img src=\"assets/gallery/$(slug).png\" width=\"260\">"
         for (name, slug) in entries]
rows = String[]
for i in 1:3:length(cells)
    chunk = cells[i:min(i + 2, end)]
    while length(chunk) < 3
        push!(chunk, "")
    end
    push!(rows, "| " * join(chunk, " | ") * " |")
end
table = join(["| | | |", "|---|---|---|", rows...], "\n")

section = """
<!-- GALLERY:BEGIN — generated by reftests/gen_readme_gallery.jl, do not edit by hand -->
Every image below is rendered by the **static core itself** — the typed
`Figure`/`Axis` API producing a Canvas2D command stream, replayed by the
bundled JS replayer (the same pipeline a compiled wasm module drives).
These are the plot types that work TODAY; the parity corpus
(`reftests/scores_core_corpus.tsv`, scored against real Makie) is a ratchet,
so this gallery only grows. Regenerate with
`julia +1.12 --project=CanvasMakie/test reftests/gen_readme_gallery.jl`.

$(table)
<!-- GALLERY:END -->"""

readme = read(README, String)
if occursin("<!-- GALLERY:BEGIN", readme)
    readme = replace(readme,
        r"<!-- GALLERY:BEGIN.*?<!-- GALLERY:END -->"s => section)
else
    # insert a Gallery section right before "## Status"
    readme = replace(readme, "## Status" => "## Gallery — what works today\n\n$(section)\n\n## Status"; count = 1)
end
write(README, readme)
println("README gallery updated: $(length(entries)) scenes")
